version: "3.8"
services:
  postgres:
    container_name: postgres
    ports:
      - "2746:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - C:/work/postgresContainer/data:/var/lib/postgresql/data
    image: postgres:12

  zookeeper:
    container_name: zookeeper
    ports:
      - "2181:3888"
      - "2888:3888"
      - "3888:3888"
    image: debezium/zookeeper:1.3

  kafka:
    container_name: kafka
    image: debezium/kafka:1.3
    environment:
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_OFFSET_STORAGE_PARTITION: 25
      KAFKA_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3
    depends_on:
      - zookeeper
    volumes:
      - C:/work/kafkaContainer/logs:/kafka/logs
      - C:/work/kafkaContainer/data:/kafka/data
    ports:
      - "9092:9092"

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    depends_on:
      - zookeeper
    ports:
    - "8082:8081"


  connect:
    container_name: connect
    image: debezium/connect:1.3
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      OFFSET_FLUSH_TIMEOUT_MS: 60000
      OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 10485760
      CONNECT_MAX_REQUEST_SIZE: 10485760
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8083:8083"

#  avro-consumer:
#    container_name: avro-consumer
#    image: debezium/connect:1.3
#    environment:
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: "avroConsumerStorageTopic"
#      OFFSET_STORAGE_TOPIC: "avroConsumerOffsetTopic"
#      BOOTSTRAP_SERVERS: "kafka:9092"
##    command:
##      sh -c "/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --property print.key=true --formatter io.confluent.kafka.formatter.AvroMessageFormatter --property schema.registry.url=http://schema-registry:8081 --topic localpostgres.public.accessmatrix_t"
#    depends_on:
#      - postgres
#      - connect
#      - zookeeper
#      - kafka
#      - schema-registry
#    ports:
#        - "8084:8084"